# Generated by Django 3.0.2 on 2020-04-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Date_and_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('Specialist', models.CharField(blank=True, max_length=100)),
                ('Experience', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('Passed_year', models.CharField(blank=True, max_length=100)),
                ('E_description', models.TextField(blank=True)),
            ],
        ),
    ]
