# Generated by Django 3.0.2 on 2020-04-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_name',
            field=models.CharField(max_length=150),
        ),
    ]
