# Generated by Django 3.0.2 on 2020-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrKiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Date_and_time', models.DateTimeField()),
            ],
        ),
    ]
