# Generated by Django 3.0.2 on 2020-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0002_drkiran'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='E1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E1_workeds_as',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E2_start_to_end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E2_workeds_as',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E3_start_to_end_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E3_workeds_as',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='E_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Passed_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Service1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Service2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Service3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
