# Generated by Django 3.0.2 on 2020-04-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0002_auto_20200415_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
