# Generated by Django 3.0.2 on 2020-04-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0003_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=150)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Date_and_time', models.CharField(max_length=100)),
            ],
        ),
    ]
