# Generated by Django 3.0.2 on 2020-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentbooking', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
